M48
; DRILL file {KiCad 5.99.0-unknown-395602b12a~131~ubuntu20.04.1} date Fri Jul 16 02:08:38 2021
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2021-07-16T02:08:38+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,5.99.0-unknown-395602b12a~131~ubuntu20.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.152
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.600
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C1.800
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T4C2.200
%
G90
G05
T1
X152.75Y-77.5
X196.25Y-77.5
X196.25Y-94.5
T2
X151.9Y-86.0
T3
X156.4Y-86.0
T4
X149.0Y-78.0
X149.0Y-94.0
X200.0Y-78.0
X200.0Y-94.0
T0
M30
